Silence error by assigning \0 instead of NULL
error: cast from pointer to smaller type 'uint8_t' (aka 'unsigned char') loses information

Test: lunch aosp_cf_arm64_phone-trunk_staging-userdebug && m libbluetooth_core_rs_bridge
Bug: 303116432
Change-Id: I230b88d4ee6be11a1014318bb323a3259d450408