Remove unused field
Fixes new code warning found by clang-r563880.

packages/modules/Bluetooth/system/btif/avrcp/avrcp_service.h:111:12: error: private field 'ct_sdp_record_handle' is not used [-Werror,-Wunused-private-field]
  111 |   uint32_t ct_sdp_record_handle = -1;
      |

Test: presubmit
Bug: 401330760
Flag: EXEMPT< dead code removal
Change-Id: Ie82106354762a55795341b31f8c812d12369fa05