Revert "Errorprone fix & enforce MethodCanBeStatic"
This reverts commit 0f45ca0eec3bfef25bcee3fc2b1555a06fa67849.

Reason for revert: Breaks build cf_x86_64_phone-trunk_staging-userdebug

packages/modules/Bluetooth/android/app/src/com/android/bluetooth/hfp/HeadsetStateMachine.java:2877: error: [MethodCanBeStatic] A private method that does not reference the enclosing instance can be static
    private void logHfpSessionMetric(BluetoothDevice device, int state) {
    ^
    (see https://errorprone.info/bugpattern/MethodCanBeStatic)
  Did you mean 'private static void logHfpSessionMetric(BluetoothDevice device, int state) {'?
1 error

Change-Id: I95163675f0b5f265685e6c8775f754c81e70a23c