floss: fix build error for clang++14
clang++14 no longer allow 'typedef struct {...} foo_t;' But require:
`struct foo_t {...};` instead.

The build error with clang++14 is:

../../../staging/bt/system/include/hardware/bt_av.h:124:9: error: C++
requires a type specifier for all declarations
typedef btav_a2dp_codec_config_t {
~~~~~~~ ^

BUG=none
TEST=./build.py

Change-Id: Ic237ccc03ae36b282354abbfbcbb3e2f08e84744